// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbbffBp8SGaIR1NSXHQVFNXAiOcSbwT48',
    appId: '1:1069850173715:web:1ffa582ca3ede1f91c3ae6',
    messagingSenderId: '1069850173715',
    projectId: 'waos-f390f',
    authDomain: 'waos-f390f.firebaseapp.com',
    storageBucket: 'waos-f390f.firebasestorage.app',
    measurementId: 'G-5D3VG9DXQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJmndm3yl3j-kJxaXGnN75Zc3Ppqd_L7A',
    appId: '1:1069850173715:android:55c6435e6a31c7c31c3ae6',
    messagingSenderId: '1069850173715',
    projectId: 'waos-f390f',
    storageBucket: 'waos-f390f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn832sB-ve4wcdqvBpqVC7fnpuhCgFAck',
    appId: '1:1069850173715:ios:e69136b892cd12821c3ae6',
    messagingSenderId: '1069850173715',
    projectId: 'waos-f390f',
    storageBucket: 'waos-f390f.firebasestorage.app',
    iosBundleId: 'com.example.biasDetect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn832sB-ve4wcdqvBpqVC7fnpuhCgFAck',
    appId: '1:1069850173715:ios:e69136b892cd12821c3ae6',
    messagingSenderId: '1069850173715',
    projectId: 'waos-f390f',
    storageBucket: 'waos-f390f.firebasestorage.app',
    iosBundleId: 'com.example.biasDetect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbbffBp8SGaIR1NSXHQVFNXAiOcSbwT48',
    appId: '1:1069850173715:web:e51624d0203e109f1c3ae6',
    messagingSenderId: '1069850173715',
    projectId: 'waos-f390f',
    authDomain: 'waos-f390f.firebaseapp.com',
    storageBucket: 'waos-f390f.firebasestorage.app',
    measurementId: 'G-2BD9MWFGZW',
  );
}
