// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8v05CXSTfdwdVUWOFDq5pK11Noux3Mo4',
    appId: '1:1030652401330:web:7db3d736fd120ca5825bab',
    messagingSenderId: '1030652401330',
    projectId: 'bias-detect',
    authDomain: 'bias-detect.firebaseapp.com',
    storageBucket: 'bias-detect.firebasestorage.app',
    measurementId: 'G-GR3TX71G27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3zbhGs-_ORe6Yhc4cZvbx8JAFGmdxzQM',
    appId: '1:1030652401330:android:a4401617449a73ac825bab',
    messagingSenderId: '1030652401330',
    projectId: 'bias-detect',
    storageBucket: 'bias-detect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMGkzTCYYwiAQPRWhzvqHxdwWh2eFjnlk',
    appId: '1:1030652401330:ios:0415c0d76cb0c669825bab',
    messagingSenderId: '1030652401330',
    projectId: 'bias-detect',
    storageBucket: 'bias-detect.firebasestorage.app',
    iosBundleId: 'com.example.biasDetect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMGkzTCYYwiAQPRWhzvqHxdwWh2eFjnlk',
    appId: '1:1030652401330:ios:0415c0d76cb0c669825bab',
    messagingSenderId: '1030652401330',
    projectId: 'bias-detect',
    storageBucket: 'bias-detect.firebasestorage.app',
    iosBundleId: 'com.example.biasDetect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8v05CXSTfdwdVUWOFDq5pK11Noux3Mo4',
    appId: '1:1030652401330:web:0293f3ecd2241634825bab',
    messagingSenderId: '1030652401330',
    projectId: 'bias-detect',
    authDomain: 'bias-detect.firebaseapp.com',
    storageBucket: 'bias-detect.firebasestorage.app',
    measurementId: 'G-FG6KXL75C7',
  );
}
